package com.rrbofficial.androiduipracticekotlin.Notifications.util

object AppConstant {

    const val NOTIFICATION_DEFAULT_CHANNEL_ID = "dn01"
    const val NOTIFICATION_DEFAULT_ID = 1001
    const val NOTIFICATION_HIGH_CHANNEL_ID = "dn02"
    const val NOTIFICATION_HIGH_ID = 1002
    const val NOTIFICATION_LOW_CHANNEL_ID = "dn03"
    const val NOTIFICATION_LOW_ID = 1003
    const val NOTIFICATION_ACTION_CHANNEL_ID = "dn04"
    const val NOTIFICATION_ACTION_ID = 1004

    const val NOTIFICATION_CONTENT_INTENT_CHANNEL_ID = "dn05"
    const val NOTIFICATION_CONTENT_INTENT_ID = 1005

    const val NOTIFICATION_ONGOING_CHANNEL_ID = "dn06"
    const val NOTIFICATION_ONGOING_INTENT_ID = 1006

    const val NOTIFICATION_CUSTOM_SOUND_CHANNEL_ID = "dn07"
    const val NOTIFICATION_CUSTOM_SOUND_INTENT_ID = 1007

    const val NOTIFICATION_BIG_TEXT_STYLE_CHANNEL_ID = "dn08"
    const val NOTIFICATION_BIG_TEXT_STYLE_INTENT_ID = 1008

    const val NOTIFICATION_INBOX_STYLE_CHANNEL_ID = "dn09"
    const val NOTIFICATION_INBOX_STYLE_INTENT_ID = 1009


    const val NOTIFICATION_BIG_PICTURE_STYLE_CHANNEL_ID = "dn10"
    const val NOTIFICATION_BIG_PICTURE_STYLE_INTENT_ID = 1010


    const val NOTIFICATION_DOWNLOAD_STYLE_CHANNEL_ID = "dn11"
    const val NOTIFICATION_DOWNLOAD_STYLE_INTENT_ID = 1011

    const val NOTIFICATION_MESSAGING_STYLE_CHANNEL_ID = "dn12"
    const val NOTIFICATION_MESSAGING_STYLE_INTENT_ID = 1012

    const val NOTIFICATION_MEDIA_STYLE_CHANNEL_ID = "dn13"
    const val NOTIFICATION_MEDIA_STYLE_INTENT_ID = 1013

    const val NOTIFICATION_CUSTOM_STYLE_CHANNEL_ID = "dn14"
    const val NOTIFICATION_CUSTOM_STYLE_INTENT_ID = 1014


    const val GROUP_1_ID = "group_01"
    const val GROUP_1_NAME = "Private group"
    const val GROUP_2_ID = "group_02"
    const val GROUP_2_NAME = "Public group"
}